name: MOCHA
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - numpy<=1.23.0
  - pytorch
  - pytorch-cuda=11.8
  - torchvision
  - pip
  - pip:
    - einops
    - sklearn
    - shutil
    - pathlib
    - matplotlib
    - tqdm
    - itertools