data_dir: './datasets/mocha60/'
data_adult2child_dir: './datasets/adult2child/'
data_bandai_dir: './datasets/bandai/'
data_Xia_dir: './datasets/Xia/'

mocha_style_names:
    ['Angry_AverageJoe', 'Happy_AverageJoe', 'Neutral_AverageJoe', 'Sad_AverageJoe', 'Scared_AverageJoe',
     'Angry_Clown', 'Happy_Clown', 'Neutral_Clown', 'Sad_Clown', 'Scared_Clown', 
     'Angry_Ogre', 'Happy_Ogre', 'Neutral_Ogre', 'Sad_Ogre', 'Scared_Ogre', 
     'Angry_Princess', 'Happy_Princess', 'Neutral_Princess', 'Sad_Princess', 'Scared_Princess', 
     'Angry_Robot', 'Happy_Robot', 'Neutral_Robot', 'Sad_Robot', 'Scared_Robot', 
     'Angry_Zombie', 'Happy_Zombie', 'Neutral_Zombie', 'Sad_Zombie', 'Scared_Zombie']

mocha_character_names:
    ['AverageJoe', 'Clown', 'Ogre', 'Princess', 'Robot', 'Zombie']

mocha_action_names:
    ['Dance',
     'Dribble_Basketball',
     'Fight',
     'Jump',
     'Crawling',
     'Crouch',
     'Run',
     'Walk',
     'Object',
     'Swing_Bat',
     'Push',
     'Sit',
     'Stumble',
     'Uneven_Floor']

# mocha_action_names:
#     ['Dance',
#      'Dribble_Basketball',
#      'Fight',
#      'Jump',
#      'Loco_Crawling',
#      'Loco_Crouch',
#      'Loco_Run',
#      'Loco_Walk',
#      'Loco_Walk_Side',
#      'Pickup_Object',
#      'Props_Object',
#      'Props_Swing_Bat',
#      'Push_and_Fall',
#      'Push_and_Fall_Backward',
#      'Push_and_Fall_Side',
#      'Push',
#      'Stats_Sit',
#      'Stumble',
#      'Uneven_Floor']
    
mocha_joints:
     ['Hips', 
      'LeftUpLeg', 'LeftLeg', 'LeftFoot', 'LeftToeBase',
      'Spine', 'Spine1', 'Spine2', 'Spine3',
      'LeftShoulder', 'LeftArm', 'LeftForeArm', 'LeftHand',
      'Neck', 'Neck1', 'Head',
      'RightShoulder', 'RightArm', 'RightForeArm', 'RightHand',
      'RightUpLeg', 'RightLeg', 'RightFoot', 'RightToeBase']

mocha_parents:
    [-1, 0, 1, 2, 3, 0, 5, 6, 7, 8, 9, 10, 11, 8, 13, 14, 8, 16, 17, 18, 0, 20, 21, 22]

ian_joints:
    ['Hips', 
     'Chest', 'Chest2', 'Chest3', 'Chest4', 
     'Neck', 'Head', 
     'RightCollar', 'RightShoulder', 'RightElbow', 'RightWrist', 
     'LeftCollar', 'LeftShoulder', 'LeftElbow', 'LeftWrist',
     'RightHip', 'RightKnee', 'RightAnkle', 'RightToe',
     'LeftHip', 'LeftKnee', 'LeftAnkle', 'LeftToe']

adult2child_joints:
    ["Hips",    
     "Spine", "Spine1", "Spine2", "Spine3",    
     "Neck", "Neck1", "Head", "HeadEnd",    
     "RightShoulder",    "RightArm",    "RightForeArm",    "RightHand",    "RightHandThumb1",    "RightHandMiddle1",    
     "LeftShoulder",    "LeftArm",    "LeftForeArm",    "LeftHand",    "LeftHandThumb1",    "LeftHandMiddle1",    
     "RightUpLeg",    "RightLeg",    "RightFoot",    "RightForeFoot", "RightToeBase",    "RightToeBaseEnd",    
     "LeftUpLeg",    "LeftLeg",    "LeftFoot",    "LeftForeFoot",    "LeftToeBase",    "LeftToeBaseEnd"]

adult2child_parents:
    [-1,  0,  1,  2,  3,  4,  5,  6,  7,  4,  9, 10, 11, 12, 12,  4, 15,
      16, 17, 18, 18,  0, 21, 22, 23, 24, 25,  0, 27, 28, 29, 30, 31]

# child002, child003 hierarchy 다름 제외
adult2child_character_names: 
    ['adult001', 'adult002', 'adult003', 'adult004', 'adult005', 'adult006', 'adult007', 'adult008', 'adult009',
     'child001', 'child004', 'child005', 'child006', 'child007', 'child008']

adult2child_action_names:
    ['-broad_jump_fwd_two_feet-',
     '-fast_punch_left-',
     '-fast_punch_right-',
     '-idle-',
     '-jog-',
     '-jump_as_high_as_you_can_in_place-',
     '-jump_with_left_leg-',
     '-jump_with_right_leg-',
     '-jump-',
     '-jumping_jacks-',
     '-kick_hard_left-',
     '-kick_hard_right-',
     '-kick_left-',
     '-kick_right-',
     '-punch_left-',
     '-punch_right-',
     '-run_and_jump-',
     '-run_as_fast_as_you_can-',
     '-skip-',
     '-throw_a_ball_left-',
     '-throw_a_ball_right-',
     '-walk-',
     '-walk_as_fast_as_you_can-',
     '-others-']

    
bandai_joints:
    ['Hips',
     'Spine', 'Chest', 'Neck', 'Head',
     'Shoulder_L', 'UpperArm_L', 'LowerArm_L', 'Hand_L',
     'Shoulder_R', 'UpperArm_R', 'LowerArm_R', 'Hand_R',
     'UpperLeg_L', 'LowerLeg_L', 'Foot_L', 'Toes_L', 
     'UpperLeg_R', 'LowerLeg_R', 'Foot_R', 'Toes_R']

bandai_parents:
    [-1, 0, 1, 2, 3, 2, 5, 6, 7, 2, 9, 10, 11, 0, 13, 14, 15, 0, 17, 18, 19]

bandai_contents:
    ['walk', 'run', 'dash', 'walk-back', 'walk-right', 'walk-left', 'bow', 'bye', 
     'guide', 'byebye', 'respond', 'call', 'kick', 'slash', 'dance']

bandai_styles:
    ['normal', 'happy', 'sad', 'angry', 'proud', 'not-confident', 'masculinity', 'feminine', 
     'childish', 'old', 'tired', 'active', 'musical', 'giant', 'chimpira']


Xia_contents:
    ['fast_punching', 'fast_walking', 'jumping', 'kicking', 'normal_walking', 'punching', 'running', 'transitions']

Xia_styles:
    ['angry', 'childlike', 'depressed', 'neutral', 'old', 'proud', 'sexy', 'strutting']

Xia_parents:
    [-1, 0, 1, 2, 3, 0, 5, 6, 7, 0, 9, 10, 11, 10, 13, 14, 15, 10, 17, 18, 19]

Xia_joints:
    ['Hips',
     'LeftUpLeg', 'LeftLeg', 'LeftFoot', 'LeftToeBase',
     'RightUpLeg', 'RightLeg', 'RightFoot', 'RightToeBase',
     'Spine', 'Spine1',
     'Neck1', 'Head',
     'LeftArm', 'LeftForeArm', 'LeftHand', 'LeftHandIndex1',
     'RightArm', 'RightForeArm', 'RightHand','RightHandIndex1']
